## This is basic continuous integration build for your Quarkus application.

name: Latest (Staging)

on:
  push:
    branches: [ develop ]

jobs:
  hugo:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'true'
    - uses: jakejarvis/hugo-build-action@master  # ...or replace 'master' with a full version tag, such as: v0.64.1
      with:
        args: --minify --buildDrafts --buildFuture
    - uses: actions/upload-artifact@master
      with:
        name: website
        path: |
         ./public
         ./Dockerfile


  container-build:
    runs-on: [ ubuntu-latest ]
    needs: hugo
    steps:
    - name: retrieve build
      id: retrieve-build
      uses: actions/download-artifact@v2
      with:
        name: website

    - name: Buildah
      id: build-container
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ secrets.IMAGE_NAME }}
        tags: latest ${{ github.sha }}
        dockerfiles: ./Dockerfile
        context: ./

    - name: Push To quay
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ secrets.IMAGE_NAME }}
        tags: latest ${{ github.sha }}
        registry: ${{ secrets.QUAY_REPO }}
        username: ${{ secrets.QUAY_USER }}
        password: ${{ secrets.QUAY_TOKEN }}
